#!/bin/bash
set -x
declare -r parent_folder=$(dirname "$(pwd)");
declare -r aports=${parent_folder}/aports;

if [[ ! -d "${aports}" ]] ; then
  mkdir "${aports}";
fi

docker run --rm -dit --env DISPLAY=":0" \
--mount type=bind,src=${aports},dst=/home/dev/aports,bind-propagation=shared \
--mount type=bind,src=/tmp/.X11-unix,dst=/tmp/.X11-unix --name apk-build apk-build:latest

